- hosts: localhost
  become: true
  tasks:
 
  - name: Remove unwanted packages before upgrades
    apt:
      name: "{{ packages_remove }}"
      state: absent
    vars:
      packages_remove:
      - chromium
 
  # - name : Add specified repository into sources list.
  #   apt_repository:
  #     repo: ppa:oguzhaninan/stacer
  #     state: present

  - name: Apt-get Update
    apt:
      update_cache: yes

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest   
  
  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Install my packages
    apt:
      name: "{{ packages_install }}"
    vars:
      packages_install:
      - aptitude
      - htop
      - ncdu
      - gnome-tweak-tool
      - vlc
      - tmux
      - nmap
      - ubuntu-restricted-extras
      - gparted
      - krita
      - filezilla
      - python-pip
      
  - name: Install Docker Prerequisites
    apt:
      name: "{{ packages_install_docker }}"
    vars:
      packages_install_docker:
      - apt-transport-https
      - ca-certificates
      - curl 
      - gnupg-agent 
      - software-properties-common

  - name: Install CLAMAV
    apt:
      name: "{{ packages_clamav }}"
    vars:
      packages_clamav:
      - clamav
      - clamav-daemon
      - clamav-freshclam
      - clamtk

  - name: Install Visual Studio code with option --classic
    snap:
      name: code
      classic: yes
  - name: Install Spotify
    snap:
      name: spotify
  - name: Install Kubectl
    snap:
      name: kubectl
      classic: yes
      
  - name: Add Docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

      
  - name: Laptop and Gnome Tweaks
    shell: |
      echo "options iwlwifi led_mode=1" >>/etc/modprobe.d/wlan.conf
      echo "options iwlcore led_mode=1" >>/etc/modprobe.d/wlan.conf
      echo "options iwlegacy led_mode=1" >>/etc/modprobe.d/wlan.conf
      gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size
      gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
      
  - name: Installation de Helm
    shell: |
      curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      helm repo add stable https://kubernetes-charts.storage.googleapis.com/
      helm repo update
   
  #Manually force bionic because at this time no release for eoane
  - name: Install Docker
    shell: |
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      sudo apt-get update
      sudo apt-get install docker-ce docker-ce-cli containerd.io -y
      sudo usermod -aG docker $USER
