- hosts: localhost
  become: true
  tasks:
 
  - name: Remove unwanted packages before upgrades
    apt:
      name: "{{ packages_remove }}"
      state: absent
    vars:
      packages_remove:
      - chromium
 
  # - name : Add specified repository into sources list.
  #   apt_repository:
  #     repo: ppa:oguzhaninan/stacer
  #     state: present

  - name: Apt-get Update
    apt:
      update_cache: yes

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest   
  
  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Install my packages
    apt:
      name: "{{ packages_install }}"
    vars:
      packages_install:
      - aptitude
      - htop
      - ncdu
      - gnome-tweak-tool
      - vlc
      - tmux
      - nmap
      - ubuntu-restricted-extras
      - gparted
      - krita
      - filezilla
      - python-pip

  - name: Install CLAMAV
    apt:
      name: "{{ packages_clamav }}"
    vars:
      packages_clamav:
      - clamav
      - clamav-daemon
      - clamav-freshclam
      - clamtk

  - name: Install Visual Studio code with option --classic
    snap:
      name: code
      classic: yes
  - name: Install Spotify
    snap:
      name: spotify
  - name: Install Kubectl
    snap:
      name: kubectl
      classic: yes

  - name: Execute the Shell commands
    shell: |
      echo "options iwlwifi led_mode=1" >>/etc/modprobe.d/wlan.conf
      echo "options iwlcore led_mode=1" >>/etc/modprobe.d/wlan.conf
      echo "options iwlegacy led_mode=1" >>/etc/modprobe.d/wlan.conf
      gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size
      gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
      curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      helm repo add stable https://kubernetes-charts.storage.googleapis.com/

